#!/usr/bin/perl -n
use Math::Trig ':pi';
sub run {eval $_[0]; die $@ if $@}
  /^\s*#\s*perl (.*)/         ? run "$1\n;print qq{\\n};"
: /^\s*#\s*include\s+"(.*)"$/ ? print `$0 src/$1`
                              : print;
